#!/usr/bin/env bash
# =====================================================================
# Set Terminal Title
# =====================================================================

_terminal_title_hook() {
    printf '\033]0;%s\007' \
        "${PWD/#$HOME/\~}"
}

# =====================================================================
# Set History Sync
# =====================================================================

_history_sync_hook() {
    history -a
    # history -n
}

# =====================================================================
# Interactive Ghost Path
# =====================================================================

GHOST_VIRTUAL_PATH="$PWD"

_update_ps1_hook() {
    local last_status=$?

    # local COLOR_PREFIX="\e[38;5;2m"

    local COLOR_BLACK="\e[38;5;0m"
    local COLOR_RED="\e[38;5;1m"
    local COLOR_GREEN="\e[38;5;2m"
    local COLOR_YELLOW="\e[38;5;3m"
    local COLOR_BLUE="\e[38;5;4m"
    local COLOR_MAGENTA="\e[38;5;5m"
    local COLOR_CYAN="\e[38;5;6m"
    local COLOR_WHITE="\e[38;5;7m"
    local COLOR_RESET="\e[0m"

    local COLOR_DARK_BLACK="\e[2;38;5;0m"
    local COLOR_DARK_RED="\e[2;38;5;1m"
    local COLOR_DARK_GREEN="\e[2;38;5;2m"
    local COLOR_DARK_YELLOW="\e[2;38;5;3m"
    local COLOR_DARK_BLUE="\e[2;38;5;4m"
    local COLOR_DARK_MAGENTA="\e[2;38;5;5m"
    local COLOR_DARK_CYAN="\e[2;38;5;6m"
    local COLOR_DARK_WHITE="\e[2;38;5;7m"

    local COLOR_BRIGHT_BLACK="\e[38;5;8m"
    local COLOR_BRIGHT_RED="\e[38;5;9m"
    local COLOR_BRIGHT_GREEN="\e[38;5;10m"
    local COLOR_BRIGHT_YELLOW="\e[38;5;11m"
    local COLOR_BRIGHT_BLUE="\e[38;5;12m"
    local COLOR_BRIGHT_MAGENTA="\e[38;5;13m"
    local COLOR_BRIGHT_CYAN="\e[38;5;14m"
    local COLOR_BRIGHT_WHITE="\e[38;5;15m"

    local COLOR_DARK_BRIGHT_BLACK="\e[2;38;5;8m"
    local COLOR_DARK_BRIGHT_RED="\e[2;38;5;9m"
    local COLOR_DARK_BRIGHT_GREEN="\e[2;38;5;10m"
    local COLOR_DARK_BRIGHT_YELLOW="\e[2;38;5;11m"
    local COLOR_DARK_BRIGHT_BLUE="\e[2;38;5;12m"
    local COLOR_DARK_BRIGHT_MAGENTA="\e[2;38;5;13m"
    local COLOR_DARK_BRIGHT_CYAN="\e[2;38;5;14m"
    local COLOR_DARK_BRIGHT_WHITE="\e[2;38;5;15m"

    local COLOR_RESET="\e[0m"

    # local prefix="\u@\h:"
    # local old_0=""
    local real=""
    # local old_1=""
    local ghost=""

    # too funky
    while test ! -d ${GHOST_VIRTUAL_PATH}; do
        GHOST_VIRTUAL_PATH=${GHOST_VIRTUAL_PATH%/*}
    done

    if [[ "${GHOST_VIRTUAL_PATH%/}"/ != "${PWD%/}"/* ]]; then
        GHOST_VIRTUAL_PATH="$PWD"
    fi

    # if [[ -d "$OLDPWD" && "${PWD%/}"/ == "${OLDPWD%/}"/* ]]; then
    #     old_0="${OLDPWD/#$HOME/\~}"
    #     real="${PWD#$OLDPWD}"
    #     ghost="${GHOST_VIRTUAL_PATH#$PWD}"
    # elif [[ -d "$OLDPWD" && "${OLDPWD%/}"/ == "${PWD%/}"/* ]]; then
    #     old_0="${PWD/#$HOME/\~}"
    #     old_1="${OLDPWD#$PWD}"
    #     ghost="${GHOST_VIRTUAL_PATH#$OLDPWD}"
    # else
    #     real="${PWD/#$HOME/\~}"
    # fi

    real="${PWD/#$HOME/\~}"
    ghost="${GHOST_VIRTUAL_PATH#$PWD}"

    PS1=""
    # PS1+="${COLOR_PREFIX}${prefix}${COLOR_RESET}"
    if test ${last_status} -eq 0; then
        # [[ -n "$old_0" ]] && \
        #     PS1+="${COLOR_GREEN}${old_0}${COLOR_RESET}"
        [[ -n "$real" ]] && \
            PS1+="${COLOR_BLUE}${real}${COLOR_RESET}"
        # [[ -n "$old_1" ]] && \
        #     PS1+="${COLOR_DARK_GREEN}${old_1}${COLOR_RESET}"
        [[ -n "$ghost" ]] && \
            PS1+="${COLOR_DARK_BLUE}${ghost}${COLOR_RESET}"
    else
        # [[ -n "$old_0" ]] && \
        #     PS1+="${COLOR_RED}${old_0}${COLOR_RESET}"
        [[ -n "$real" ]] && \
            PS1+="${COLOR_YELLOW}${real}${COLOR_RESET}"
        # [[ -n "$old_1" ]] && \
        #     PS1+="${COLOR_DARK_RED}${old_1}${COLOR_RESET}"
        [[ -n "$ghost" ]] && \
            PS1+="${COLOR_DARK_YELLOW}${ghost}${COLOR_RESET}"
        PS1+=" ${COLOR_RED}(${last_status})${COLOR_RESET}"
    fi
    PS1+='\n✨ '
}

PROMPT_COMMAND+=(_terminal_title_hook)
PROMPT_COMMAND+=(_history_sync_hook)
PROMPT_COMMAND+=(_update_ps1_hook)
