#!/usr/bin/env bash
# =====================================================================
# Set Terminal Title
# =====================================================================

_terminal_title_hook() {
    printf '\033]0;%s\007' \
        "${PWD/#$HOME/\~}"
}

# =====================================================================
# Set History Sync
# =====================================================================

_history_sync_hook() {
    history -a
    # history -n
}

# =====================================================================
# Interactive Ghost Path
# =====================================================================

GHOST_VIRTUAL_PATH="$PWD"

_update_ps1_hook() {
    local last_status=$?

    # local COLOR_PREFIX="\e[38;5;2m"
    local COLOR_OLD_0="\e[38;5;3m"
    local COLOR_OLD_1="\e[2;38;5;3m"
    local COLOR_REAL="\e[38;5;4m"
    local COLOR_GHOST="\e[2;38;5;4m"
    local COLOR_OK="\e[38;5;2m"
    local COLOR_ERR="\e[38;5;1m"
    local COLOR_RESET="\e[0m"

    # local prefix="\u@\h:"
    local old_0=""
    local real=""
    local old_1=""
    local ghost=""

    if [[ "${GHOST_VIRTUAL_PATH%/}"/ != "${PWD%/}"/* ]]; then
        GHOST_VIRTUAL_PATH="$PWD"
    fi

    if [[ -n "$OLDPWD" && "${PWD%/}"/ == "${OLDPWD%/}"/* ]]; then
        old_0="${OLDPWD/#$HOME/\~}"
        real="${PWD#$OLDPWD}"
        ghost="${GHOST_VIRTUAL_PATH#$PWD}"
    elif [[ -n "$OLDPWD" && "${OLDPWD%/}"/ == "${PWD%/}"/* ]]; then
        old_0="${PWD/#$HOME/\~}"
        old_1="${OLDPWD#$PWD}"
        ghost="${GHOST_VIRTUAL_PATH#$OLDPWD}"
    else
        real="${PWD/#$HOME/\~}"
    fi

    local status_color=$COLOR_ERR
    test ${last_status} -eq 0 && status_color=$COLOR_OK

    PS1=""
    # PS1+="${COLOR_PREFIX}${prefix}${COLOR_RESET}"
    [[ -n "$old_0" ]] && \
        PS1+="${COLOR_OLD_0}${old_0}${COLOR_RESET}"
    [[ -n "$real" ]] && \
        PS1+="${COLOR_REAL}${real}${COLOR_RESET}"
    [[ -n "$old_1" ]] && \
        PS1+="${COLOR_OLD_1}${old_1}${COLOR_RESET}"
    [[ -n "$ghost" ]] && \
        PS1+="${COLOR_GHOST}${ghost}${COLOR_RESET}"
    PS1+=" ${status_color}(${last_status})${COLOR_RESET}"
    PS1+='\n# '
}

PROMPT_COMMAND+=(_terminal_title_hook)
PROMPT_COMMAND+=(_history_sync_hook)
PROMPT_COMMAND+=(_update_ps1_hook)
