syntax on

highlight Comment       ctermfg=darkgrey
highlight String        ctermfg=darkcyan
highlight Keyword       ctermfg=darkyellow
highlight Search        ctermfg=black   ctermbg=darkyellow
highlight LineNr        ctermfg=brown   ctermbg=NONE
highlight LineNrAbove   ctermfg=238     ctermbg=NONE
highlight LineNrBelow   ctermfg=238     ctermbg=NONE
highlight Normal        ctermfg=white   ctermbg=NONE

highlight default link cComment Comment
highlight default link cString String
highlight default link cKeyword Keyword

function! s:syntax_c()
    setlocal syntax=off
    syntax clear
    syntax region cComment start="/\*" end="\*/" extend fold
    syntax region cComment start="//" skip="\\$" end="$" keepend
    syntax region cString start=+L\="+ skip=+\\\\\|\\"+ end=+"+
    syntax keyword cKeyword
      \ if else
      \ switch case default
      \ while for do continue
      \ break goto return
    syntax sync ccomment cCommentB minlines=50
endfunction

function! s:syntax_c3()
    call s:syntax_c()
    syntax region cComment start="<\*" end="\*>" extend fold
    syntax keyword cKeyword
      \ module import
      \ try catch
      \ foreach foreach_r
      \ nextcase
      \ def alias faultdef fn macro fault bitstruct interface
      \ defer
      \ cast asm null true false
endfunction

function! s:syntax_sh()
    syntax sync ccomment shComment minlines=1
endfunction

augroup custom_syntax
    autocmd!
    autocmd FileType c,cpp call s:syntax_c()
    autocmd FileType c3 call s:syntax_c3()
    autocmd FileType sh call s:syntax_sh()
augroup END

set hls
set number
set relativenumber
set scrolloff=5
set nocompatible
set backspace=indent,eol,start
set wildmenu
set wildmode=list:longest
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set cindent
set smartindent
set ignorecase
set smartcase
set hidden
set path+=**
set list listchars=tab:>·,trail:█,extends:>,precedes:<
set mouse=a
set mousemodel=popup
set laststatus=2
set statusline=%<%{expand('%:~:.')}%h%m%r%=%l/%L

aunmenu PopUp
anoremenu PopUp.Copy "+yiw
vnoremenu PopUp.Copy "+y
anoremenu PopUp.Cut "+diw
vnoremenu PopUp.Cut "+x
anoremenu PopUp.Paste "+gP
vnoremenu PopUp.Paste "+P
vnoremenu PopUp.Delete "_x

noremap <silent> <ESC>L <C-W>l
noremap <silent> <ESC>H <C-W>h
noremap <silent> <ESC>J <C-W>j
noremap <silent> <ESC>K <C-W>k
noremap <silent> <SPACE>m <CMD>popup PopUp<CR>
noremap! <silent> <ESC>L <ESC><C-W>l
noremap! <silent> <ESC>H <ESC><C-W>h
noremap! <silent> <ESC>J <ESC><C-W>j
noremap! <silent> <ESC>K <ESC><C-W>k

set t_Co=256

augroup CustomHighlights
    autocmd!
    autocmd ColorScheme * highlight Cursor       ctermbg=231 ctermfg=233 cterm=NONE
    autocmd ColorScheme * highlight Normal       ctermbg=NONE ctermfg=231 cterm=NONE
    autocmd ColorScheme * highlight NormalNC     ctermbg=NONE ctermfg=231 cterm=NONE
    autocmd ColorScheme * highlight StatusLine   ctermbg=NONE ctermfg=189 cterm=NONE
    autocmd ColorScheme * highlight StatusLineNC ctermbg=NONE ctermfg=189 cterm=NONE
    autocmd ColorScheme * highlight MsgArea      ctermbg=NONE ctermfg=189 cterm=NONE
    autocmd ColorScheme * highlight ModeMsg      ctermbg=NONE ctermfg=189 cterm=NONE
    autocmd ColorScheme * highlight Visual       ctermbg=239 ctermfg=NONE cterm=NONE
    autocmd ColorScheme * highlight MatchParen   ctermbg=59  ctermfg=215 cterm=NONE
    autocmd ColorScheme * highlight Identifier   ctermbg=NONE ctermfg=208 cterm=NONE
    autocmd ColorScheme * highlight SignColumn   ctermbg=NONE ctermfg=NONE cterm=NONE
    autocmd ColorScheme * highlight Pmenu        ctermbg=236 ctermfg=244 cterm=NONE
    autocmd ColorScheme * highlight PmenuSel     ctermbg=242 ctermfg=231 cterm=NONE
    autocmd ColorScheme * highlight NormalFloat  ctermbg=236 ctermfg=189 cterm=NONE
    autocmd ColorScheme * highlight FloatBorder  ctermbg=NONE ctermfg=242 cterm=NONE
    autocmd ColorScheme * highlight ColorColumn  ctermbg=197 ctermfg=NONE cterm=NONE
    autocmd ColorScheme * highlight DiffAdd      ctermbg=22  ctermfg=NONE cterm=NONE
    autocmd ColorScheme * highlight DiffChange   ctermbg=17  ctermfg=NONE cterm=NONE
    autocmd ColorScheme * highlight DiffDelete   ctermbg=52  ctermfg=NONE cterm=NONE
    autocmd ColorScheme * highlight WinSeparator ctermbg=NONE ctermfg=241 cterm=NONE
    autocmd ColorScheme * highlight CursorLineNr ctermbg=NONE ctermfg=215 cterm=NONE
    autocmd ColorScheme * highlight LineNr       ctermbg=NONE ctermfg=241 cterm=NONE
    autocmd ColorScheme * highlight LineNrAbove  ctermbg=NONE ctermfg=241 cterm=NONE
    autocmd ColorScheme * highlight LineNrBelow  ctermbg=NONE ctermfg=241 cterm=NONE
    autocmd ColorScheme * highlight Constant     ctermbg=NONE ctermfg=197 cterm=NONE
    autocmd ColorScheme * highlight String       ctermbg=NONE ctermfg=144 cterm=NONE
    autocmd ColorScheme * highlight Special      ctermbg=NONE ctermfg=177 cterm=NONE
    autocmd ColorScheme * highlight Comment      ctermbg=NONE ctermfg=241 cterm=NONE
    autocmd ColorScheme * highlight Whitespace   ctermbg=NONE ctermfg=241 cterm=NONE
    autocmd ColorScheme * highlight PreProc      ctermbg=NONE ctermfg=162 cterm=NONE
    autocmd ColorScheme * highlight PreCondit    ctermbg=NONE ctermfg=208 cterm=NONE
    autocmd ColorScheme * highlight Type         ctermbg=NONE ctermfg=34  cterm=NONE
    autocmd ColorScheme * highlight Operator     ctermbg=NONE ctermfg=34  cterm=NONE
    autocmd ColorScheme * highlight Statement    ctermbg=NONE ctermfg=220 cterm=NONE
    autocmd ColorScheme * highlight Function     ctermbg=NONE ctermfg=111 cterm=NONE
    autocmd ColorScheme * highlight Pmenu          ctermfg=245 ctermbg=236
    autocmd ColorScheme * highlight PmenuSel       ctermfg=231 ctermbg=241
    autocmd ColorScheme * highlight PmenuMatch     ctermfg=81  ctermbg=235
    autocmd ColorScheme * highlight PmenuMatchSel  ctermfg=81  ctermbg=60
    autocmd ColorScheme * highlight link PmenuKind      Pmenu
    autocmd ColorScheme * highlight link PmenuKindSel   PmenuSel
    autocmd ColorScheme * highlight link PmenuExtra     Pmenu
    autocmd ColorScheme * highlight link PmenuExtraSel  PmenuSel
    autocmd ColorScheme * highlight PmenuSbar      ctermbg=235
    autocmd ColorScheme * highlight PmenuThumb     ctermbg=238
augroup END

colorscheme desert
