#!/bin/bash

# Use Default Value if Null or Unset.
: ${VAR:-default}

# Use Default Value if Unset.
: ${VAR-default}

# Assign Default Value if Null or Unset.
: ${VAR:=default}

# Assign Default Value if Unset.
: ${VAR=default}

# Indicate Error if Null or Unset.
: ${VAR:?"Null or unset"}

# Indicate Error if Unset.
: ${VAR?"Unset"}

# Use Alternative Value if Set and Not Null.
: ${VAR:+alternative}

# Use Alternative Value if Set.
: ${VAR+alternative}

# String Length.
: ${#VAR}

# Remove Smallest Suffix Pattern.
: ${VAR%word}

# Remove Largest Suffix Pattern.
: ${VAR%%word}

# Remove Smallest Prefix Pattern.
: ${VAR#word}

# Remove Largest Prefix Pattern.
: ${VAR##word}

: ${string//pattern/replacement}：替换所有匹配的模式。
: ${string/pattern/replacement}：替换第一个匹配的模式。
: ${string/#pattern/replacement}：替换开头的匹配模式。
: ${string/%pattern/replacement}：替换结尾的匹配模式。
